Added integrations tests for checking workflow creation and update sc…
eirsep/alerting pull request #1
Opened 2023-01-27 18:49 UTC by stevanbz

…enario

Signed-off-by: Stevan Buzejic <buzejic.stevan@gmail.com>

*Issue #, if available:*

*Description of changes:*

*CheckList:*
[ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-02-23 03:15 UTC, eirsep requested changes
Thanks for the changes Stevan.

Took an initial look. Plz address these comments while I take a deeper look.

2023-02-23 03:15 UTC, eirsep commented on alerting/src/main/kotlin/org/opensearch/alerting/model/workflow/WorkflowRunResult.kt
> -data class WorkflowRunResult {
we should return list of monitor run results within this class with info from each delegate monitor run.

2023-02-23 03:15 UTC, eirsep commented on alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt
> +
let's add java docs for classes and comments for methods having complicated logic

2023-02-23 03:15 UTC, eirsep commented on alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt
> +            .setRefreshPolicy(transformedRequest.refreshPolicy)
plz remove refresh policy
we will always choose to refresh immediately.

2023-02-23 03:15 UTC, eirsep commented on alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt
> +                    // TODO - uncomment once the workflow metadata is added
can this be uncommented?

2023-02-23 03:15 UTC, eirsep commented on alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt
> +            return client.suspendUntil { delete(deleteRequest, it) }
how are we handling failure in deletion?

2023-02-23 03:15 UTC, eirsep commented on alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt
> +/*
We also need to make changes in TransportDeleteMonitorAction to stop a monitor from being deleted if its a part of an existing composite workflow sequence as a delegate monitor.

2023-02-23 03:15 UTC, eirsep commented on alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt
> +            val deleteRequest = DeleteRequest(ScheduledJob.SCHEDULED_JOBS_INDEX, "${workflow.id}-metadata")
plz add error handling

2023-02-23 03:15 UTC, eirsep commented on alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt
> +            return client.suspendUntil { delete(deleteRequest, it) }
add debug logs "deleted monitor $monitorId"

2023-02-23 03:15 UTC, eirsep commented on alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt
> +            val deleteRequest = DeleteRequest(ScheduledJob.SCHEDULED_JOBS_INDEX, "${workflow.id}-metadata")
add debug logs "deleted monitor $monitorMetadata"

2023-02-23 03:15 UTC, eirsep commented on alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexCompositeWorkflowAction.kt
> -        listener: ActionListener<IndexWorkflowResponse>
why are we not throwing through the listener?

2023-02-23 03:15 UTC, eirsep commented on alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexCompositeWorkflowAction.kt
>      ) {
plz add javadocs for classes and comments for complicated logic

2023-02-23 03:15 UTC, eirsep commented on alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexCompositeWorkflowAction.kt
> +        val compositeInput = request.workflow.inputs[0] as CompositeInput
lets first validate that the input is a composite input.

2023-02-23 03:15 UTC, eirsep commented on alerting/src/test/kotlin/org/opensearch/alerting/WorkflowMonitorIT.kt
> +    fun `test get workflow`() {
test get workflow for invalid id?

2023-02-23 03:15 UTC, eirsep commented on alerting/src/test/kotlin/org/opensearch/alerting/WorkflowMonitorIT.kt
> +    fun `test delete workflow`() {
test delete workflow for invalid id

2023-02-23 03:15 UTC, eirsep commented on alerting/src/test/kotlin/org/opensearch/alerting/WorkflowMonitorIT.kt
> +    fun `test create workflow duplicate delegate failure`() {
test update for all these failure cases

2023-02-23 03:15 UTC, eirsep commented on alerting/src/test/kotlin/org/opensearch/alerting/WorkflowMonitorIT.kt
> +    fun `test create workflow chained findings order not correct failure`() {
test delete monitor before workflow is deleted and this monitor is delegate in that sequence

2023-02-23 16:56 UTC, stevanbz commented
> Thanks for the changes Stevan.
> 
> Took an initial look. Plz address these comments while I take a deeper look.

Tnx Will do so. Tnx for constructive feedback

2023-02-23 16:59 UTC, stevanbz commented on alerting/src/main/kotlin/org/opensearch/alerting/model/workflow/WorkflowRunResult.kt
> -data class WorkflowRunResult {
> we should return list of monitor run results within this class with info from each delegate monitor run.

Yeah - I agree. That's in another PR that contains execution of the workflow changes. Check it out [here](https://github.com/stevanbz/alerting/pull/1/files#diff-eed2526392090b3375d9d1368929535eb005e0da86267673817f4231cbe12210)

2023-02-23 17:18 UTC, stevanbz commented on alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt
> +                    // TODO - uncomment once the workflow metadata is added
Well no - because the workflow metadata are not added still

2023-02-23 17:22 UTC, stevanbz commented on alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt
> +            return client.suspendUntil { delete(deleteRequest, it) }
> how are we handling failure in deletion?

Well we are calling delete(deleteRequest, it) as a lambda. You can see that second parameter of delete function call is it -> which is ActionListener forwarded to a delete function.

2023-02-23 21:19 UTC, stevanbz commented on alerting/src/test/kotlin/org/opensearch/alerting/WorkflowMonitorIT.kt
> +    fun `test create workflow chained findings order not correct failure`() {
good point. will test that

2023-02-24 14:14 UTC, stevanbz commented on alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt
> +            val deleteRequest = DeleteRequest(ScheduledJob.SCHEDULED_JOBS_INDEX, "${workflow.id}-metadata")
So just FYI - right now there is no existing workflow metadata.

2023-02-24 15:49 UTC, stevanbz commented on alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt
> +/*
Very good point Sashank!

2023-02-24 15:50 UTC, stevanbz commented on alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt
> +
I agree. This class is pretty much obvious and the methods inside it are pretty much descriptive. So probably for indexing the workflow

2023-02-24 16:02 UTC, stevanbz commented on alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexCompositeWorkflowAction.kt
> +        val compositeInput = request.workflow.inputs[0] as CompositeInput
done

2023-02-24 16:15 UTC, stevanbz commented on alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexCompositeWorkflowAction.kt
> -        listener: ActionListener<IndexWorkflowResponse>
Because the program flow will continue to execute despite if we go through the listener.onFailure. 
So all validateXYZ methods are throwing the exception which is caught in the main flow. And in that case after returning error message to a client the program flow is interrupted. Check it out here:
https://github.com/eirsep/alerting/pull/1/files#diff-e46d42c34f46ce03ca8293d677a7628dc2ef28e285f0b56593408652564c5b57R172

2026-04-15 15:01 UTC, closed without merging